Inventory:
  Rows: 1
  Name: Server Selector
Selector:
  Material: COMPASS
  Display_Name: '&4Server Selector'
Server_Slots:
  '1':
    Amount: 1
    Target_Server: lobby1
    Display_Name: '&aLobby 1'
    Material: PAPER
  '2':
    Amount: 1
    Target_Server: lobby2
    Display_Name: '&aLobby 2'
    Material: PAPER
Version: DEFAULT