InventoryRows: 1
InventoryName: Server Selector
ItemStack:
  ==: org.bukkit.inventory.ItemStack
  type: COMPASS
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: "\xa74Server Selector"
Servers:
- PAPER:1:Lobby 1:lobby1:a:1
- PAPER:1:Lobby 2:lobby2:a:2
Version: DEFAULT