author: CombatTag
description: LobbySwitch plugin
main: com.cypher.LobbySwitch
name: LobbySwitch
version: 0.2.3
commands:
  lobbyswitch:
    description: Lobby switch main command.
    aliases: [ls]
    permission: lobbyswitch
    usage: /lobbyswitch